import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  container: {
    alignItems: "stretch",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  title: {
    color: "#111827",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 10,
    textAlign: "center",
  },
  body: {
    color: "#4b5563",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    color: "#111827",
    fontSize: 16,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  textButton: {
    alignItems: "center",
    marginTop: 16,
    paddingVertical: 8,
  },
  textButtonText: {
    color: "#2563eb",
    fontSize: 15,
    fontWeight: "700",
  },
  disabledButton: {
    opacity: 0.6,
  },
  error: {
    color: "#b91c1c",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
    textAlign: "center",
  },
  learnContent: {
    padding: 20,
    paddingBottom: 40,
  },
  headerRow: {
    gap: 14,
    marginBottom: 18,
  },
  eyebrow: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 4,
  },
  signOutButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  signOutButtonText: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "800",
  },
  backButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  backButtonText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "800",
  },
  optionGrid: {
    gap: 14,
  },
  optionPanel: {
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  optionTitle: {
    color: "#0f172a",
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 8,
  },
  optionText: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 23,
  },
  emptyPanel: {
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
  },
  sectionTitle: {
    color: "#0f172a",
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 12,
  },
  gradeGrid: {
    gap: 10,
  },
  gradeButton: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  gradeButtonTitle: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 4,
  },
  gradeButtonText: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  progressBand: {
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 18,
    padding: 16,
  },
  progressTitle: {
    color: "#0f172a",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 10,
  },
  progressTrack: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    height: 12,
    marginBottom: 10,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "#16a34a",
    height: 12,
  },
  progressText: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  lessonLayout: {
    gap: 16,
  },
  unitList: {
    gap: 12,
  },
  unitSection: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    paddingBottom: 12,
  },
  lessonButton: {
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    padding: 12,
  },
  lessonButtonTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  lessonButtonMeta: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
    textTransform: "capitalize",
  },
  lessonButtonGoal: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 5,
  },
  lessonPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  lessonConcept: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  lessonTitle: {
    color: "#0f172a",
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 8,
  },
  lessonExplain: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 14,
  },
  exampleBlock: {
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  questionBlock: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    padding: 12,
  },
  exampleLabel: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  exampleText: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
    marginBottom: 10,
  },
  tenFrame: {
    borderColor: "#0f172a",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    flexWrap: "wrap",
    height: 116,
    marginBottom: 16,
    maxWidth: 280,
    overflow: "hidden",
    width: "100%",
  },
  tenCell: {
    alignItems: "center",
    borderColor: "#0f172a",
    borderWidth: 1,
    height: 56,
    justifyContent: "center",
    width: "20%",
  },
  tenCellFilled: {
    backgroundColor: "#f97316",
  },
  visualRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  visualOperator: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "900",
  },
  dotWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    maxWidth: 180,
  },
  dot: {
    alignItems: "center",
    backgroundColor: "#22c55e",
    borderRadius: 14,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  dotRemoved: {
    backgroundColor: "#fecaca",
    borderColor: "#dc2626",
    borderWidth: 2,
  },
  removedMark: {
    color: "#991b1b",
    fontSize: 16,
    fontWeight: "900",
  },
  numberLine: {
    borderTopColor: "#0f172a",
    borderTopWidth: 3,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 44,
    marginTop: 34,
    paddingTop: 0,
  },
  numberTick: {
    alignItems: "center",
    marginTop: -12,
    width: 14,
  },
  tickLine: {
    backgroundColor: "#0f172a",
    height: 16,
    width: 2,
  },
  tickText: {
    color: "#0f172a",
    fontSize: 9,
    fontWeight: "800",
    marginTop: 3,
  },
  jumpText: {
    bottom: -34,
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "800",
    left: 0,
    position: "absolute",
  },
  baseTenRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 18,
    marginBottom: 16,
  },
  tenRodColumn: {
    flexDirection: "row",
    gap: 8,
  },
  tenRod: {
    backgroundColor: "#60a5fa",
    borderColor: "#1d4ed8",
    borderRadius: 6,
    borderWidth: 1,
    height: 110,
    width: 24,
  },
  skipRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 16,
  },
  skipBubble: {
    alignItems: "center",
    backgroundColor: "#e0f2fe",
    borderColor: "#0284c7",
    borderRadius: 8,
    borderWidth: 1,
    height: 54,
    justifyContent: "center",
    width: 54,
  },
  skipText: {
    color: "#075985",
    fontSize: 18,
    fontWeight: "900",
  },
  skipNext: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "900",
  },
  measurementBox: {
    marginBottom: 16,
  },
  pencil: {
    backgroundColor: "#facc15",
    borderRadius: 8,
    height: 22,
    marginBottom: 10,
    maxWidth: 260,
    width: "90%",
  },
  clipRow: {
    flexDirection: "row",
    gap: 6,
  },
  paperClip: {
    borderColor: "#64748b",
    borderRadius: 10,
    borderWidth: 2,
    height: 34,
    width: 20,
  },
  clock: {
    alignSelf: "flex-start",
    borderColor: "#0f172a",
    borderRadius: 70,
    borderWidth: 3,
    height: 140,
    marginBottom: 16,
    position: "relative",
    width: 140,
  },
  clockNumber: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "900",
    position: "absolute",
  },
  clockTwelve: {
    left: 58,
    top: 8,
  },
  clockThree: {
    right: 12,
    top: 60,
  },
  clockSix: {
    bottom: 8,
    left: 64,
  },
  clockNine: {
    left: 12,
    top: 60,
  },
  hourHand: {
    backgroundColor: "#0f172a",
    height: 4,
    left: 70,
    position: "absolute",
    top: 68,
    width: 42,
  },
  minuteHand: {
    backgroundColor: "#0f172a",
    height: 54,
    left: 68,
    position: "absolute",
    top: 18,
    width: 4,
  },
  shapeRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 18,
    marginBottom: 16,
  },
  triangle: {
    borderBottomColor: "#f97316",
    borderBottomWidth: 58,
    borderLeftColor: "transparent",
    borderLeftWidth: 32,
    borderRightColor: "transparent",
    borderRightWidth: 32,
    height: 0,
    width: 0,
  },
  squareShape: {
    backgroundColor: "#22c55e",
    height: 58,
    width: 58,
  },
  circleShape: {
    backgroundColor: "#60a5fa",
    borderRadius: 29,
    height: 58,
    width: 58,
  },
  practicePrompt: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 25,
    marginBottom: 12,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 12,
  },
  choiceButton: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 78,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  choiceCorrect: {
    backgroundColor: "#bbf7d0",
    borderColor: "#16a34a",
  },
  choiceIncorrect: {
    backgroundColor: "#fecaca",
    borderColor: "#dc2626",
  },
  choiceButtonText: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "900",
  },
  feedbackText: {
    color: "#334155",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 22,
    marginBottom: 12,
  },
  masteryBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    marginTop: 4,
    padding: 12,
  },
  masteryLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 3,
    textTransform: "uppercase",
  },
  masteryValue: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
});
