import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  container: {
    alignItems: "stretch",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  title: {
    color: "#111827",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 10,
    textAlign: "center",
  },
  homeTitle: {
    color: "#0f172a",
    fontSize: 34,
    lineHeight: 38,
    marginBottom: 0,
    textAlign: "left",
  },
  body: {
    color: "#4b5563",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    color: "#111827",
    fontSize: 16,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#2563eb",
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  textButton: {
    alignItems: "center",
    marginTop: 16,
    paddingVertical: 8,
  },
  textButtonText: {
    color: "#2563eb",
    fontSize: 15,
    fontWeight: "700",
  },
  disabledButton: {
    opacity: 0.6,
  },
  error: {
    color: "#b91c1c",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
    textAlign: "center",
  },
  appShell: {
    backgroundColor: "#dff7ff",
    flex: 1,
  },
  learnContent: {
    padding: 18,
    paddingBottom: 118,
    position: "relative",
  },
  learnScreen: {
    backgroundColor: "#dff7ff",
  },
  learnBackgroundTop: {
    backgroundColor: "#7dd3fc",
    borderBottomLeftRadius: 120,
    borderBottomRightRadius: 54,
    height: 230,
    left: -40,
    opacity: 0.9,
    position: "absolute",
    right: -36,
    top: 0,
  },
  learnBackgroundBottom: {
    backgroundColor: "#fde68a",
    borderTopLeftRadius: 90,
    height: 260,
    left: -50,
    opacity: 0.9,
    position: "absolute",
    right: -70,
    top: 270,
  },
  floatingMathLayer: {
    height: 260,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  floatingMathToken: {
    alignItems: "center",
    borderRadius: 18,
    height: 42,
    justifyContent: "center",
    position: "absolute",
    shadowColor: "#0f172a",
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    width: 42,
  },
  floatingMathTokenWarm: {
    backgroundColor: "#fb7185",
  },
  floatingMathTokenCool: {
    backgroundColor: "#34d399",
  },
  floatingMathText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  heroPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#bae6fd",
    borderRadius: 28,
    borderWidth: 2,
    marginBottom: 16,
    marginTop: 82,
    padding: 18,
    shadowColor: "#0f172a",
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  headerRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 14,
    justifyContent: "space-between",
  },
  headerCopy: {
    flex: 1,
  },
  eyebrow: {
    color: "#0f766e",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 6,
  },
  heroSubtitle: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 22,
    marginTop: 2,
  },
  signOutButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
    borderRadius: 18,
    borderWidth: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  signOutButtonText: {
    color: "#9a3412",
    fontSize: 13,
    fontWeight: "800",
  },
  backButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderColor: "#93c5fd",
    borderRadius: 18,
    borderWidth: 2,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
    shadowColor: "#0f172a",
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  backButtonText: {
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "800",
  },
  optionGrid: {
    gap: 16,
  },
  optionPanel: {
    borderRadius: 24,
    borderWidth: 0,
    minHeight: 178,
    overflow: "hidden",
    padding: 20,
    shadowColor: "#0f172a",
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
  },
  optionPanelGames: {
    backgroundColor: "#a78bfa",
  },
  optionPanelLessons: {
    backgroundColor: "#2dd4bf",
  },
  optionIconBubble: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderRadius: 22,
    height: 54,
    justifyContent: "center",
    marginBottom: 14,
    width: 54,
  },
  optionIconText: {
    fontSize: 28,
  },
  optionKicker: {
    color: "rgba(255, 255, 255, 0.88)",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  optionTitle: {
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "900",
    marginBottom: 8,
  },
  optionText: {
    color: "#ffffff",
    fontSize: 16,
    lineHeight: 23,
  },
  emptyPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#f9a8d4",
    borderRadius: 24,
    borderWidth: 2,
    padding: 18,
    shadowColor: "#0f172a",
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
  },
  gameList: {
    gap: 12,
  },
  gameCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f9a8d4",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    gap: 12,
    padding: 16,
    shadowColor: "#0f172a",
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
  },
  gameCardBadge: {
    alignItems: "center",
    backgroundColor: "#fef3c7",
    borderColor: "#f59e0b",
    borderRadius: 8,
    borderWidth: 2,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  gameCardBadgeText: {
    color: "#92400e",
    fontSize: 28,
    fontWeight: "900",
  },
  gameCardCopy: {
    flex: 1,
  },
  gameCardTitle: {
    color: "#0f172a",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 4,
  },
  gameCardText: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  gameCardAction: {
    color: "#2563eb",
    fontSize: 15,
    fontWeight: "900",
  },
  gameScreen: {
    backgroundColor: "#ecfeff",
    flex: 1,
    padding: 18,
  },
  gameHud: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  gameHudPill: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#bae6fd",
    borderRadius: 8,
    borderWidth: 2,
    flex: 1,
    paddingVertical: 12,
  },
  gameHudLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  gameHudValue: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "900",
  },
  makeTenEquation: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f59e0b",
    borderRadius: 8,
    borderWidth: 3,
    justifyContent: "center",
    marginBottom: 16,
    minHeight: 148,
    padding: 20,
  },
  makeTenEquationText: {
    color: "#0f172a",
    fontSize: 42,
    fontWeight: "900",
    textAlign: "center",
  },
  gameCompletePanel: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#86efac",
    borderRadius: 8,
    borderWidth: 3,
    gap: 12,
    padding: 22,
  },
  celebrationText: {
    color: "#16a34a",
    fontSize: 34,
    fontWeight: "900",
    textAlign: "center",
  },
  gameCompleteScore: {
    color: "#0f172a",
    fontSize: 30,
    fontWeight: "900",
    textAlign: "center",
  },
  gameCompleteCopy: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 6,
    textAlign: "center",
  },
  makeTenPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#f9a8d4",
    borderRadius: 24,
    borderWidth: 2,
    padding: 18,
    shadowColor: "#0f172a",
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
  },
  makeTenHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  makeTenScorePill: {
    alignItems: "center",
    backgroundColor: "#dcfce7",
    borderColor: "#86efac",
    borderRadius: 18,
    borderWidth: 2,
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  makeTenScoreText: {
    color: "#166534",
    fontSize: 16,
    fontWeight: "900",
  },
  makeTenTarget: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#fef3c7",
    borderColor: "#f59e0b",
    borderRadius: 60,
    borderWidth: 3,
    height: 118,
    justifyContent: "center",
    marginBottom: 14,
    marginTop: 6,
    width: 118,
  },
  makeTenTargetNumber: {
    color: "#92400e",
    fontSize: 52,
    fontWeight: "900",
  },
  makeTenFeedback: {
    color: "#0f172a",
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 24,
    marginBottom: 14,
    minHeight: 48,
    textAlign: "center",
  },
  makeTenTileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
    marginBottom: 18,
  },
  makeTenTile: {
    alignItems: "center",
    backgroundColor: "#e0f2fe",
    borderColor: "#38bdf8",
    borderRadius: 8,
    borderWidth: 2,
    height: 64,
    justifyContent: "center",
    width: 64,
  },
  makeTenTileSelected: {
    backgroundColor: "#c4b5fd",
    borderColor: "#7c3aed",
  },
  makeTenTileText: {
    color: "#0f172a",
    fontSize: 26,
    fontWeight: "900",
  },
  gameStatsPanel: {
    borderTopColor: "#e2e8f0",
    borderTopWidth: 1,
    marginTop: 18,
    paddingTop: 18,
    width: "100%",
  },
  recentRunList: {
    gap: 8,
    marginTop: 12,
    width: "100%",
  },
  recentRunRow: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  recentRunRank: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "900",
    width: 34,
  },
  recentRunScore: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
    fontWeight: "900",
  },
  recentRunDate: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "800",
  },
  makeTenPairGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
    marginBottom: 18,
  },
  makeTenPairCard: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 86,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  makeTenPairCardMatched: {
    backgroundColor: "#bbf7d0",
    borderColor: "#16a34a",
  },
  makeTenPairText: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "900",
  },
  sectionTitle: {
    color: "#0f172a",
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 12,
  },
  gradeGrid: {
    gap: 10,
  },
  gradeButton: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  primaryNavAction: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#0ea5e9",
    borderRadius: 8,
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryNavActionText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  profilePanel: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#bae6fd",
    borderRadius: 8,
    borderWidth: 2,
    padding: 18,
    shadowColor: "#0f172a",
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
  },
  profileAvatar: {
    alignItems: "center",
    backgroundColor: "#0ea5e9",
    borderRadius: 36,
    height: 72,
    justifyContent: "center",
    marginBottom: 12,
    width: 72,
  },
  profileAvatarText: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "900",
  },
  profileName: {
    color: "#0f172a",
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 4,
    textAlign: "center",
  },
  profileEmail: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 18,
    textAlign: "center",
  },
  profileStatRow: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  profileStat: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  profileStatValue: {
    color: "#0f172a",
    fontSize: 22,
    fontWeight: "900",
  },
  profileStatLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  bottomNav: {
    alignItems: "center",
    backgroundColor: "#101820",
    borderTopColor: "#26323d",
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    left: 0,
    paddingBottom: 22,
    paddingHorizontal: 8,
    paddingTop: 10,
    position: "absolute",
    right: 0,
  },
  navTab: {
    alignItems: "center",
    flex: 1,
    gap: 3,
    minHeight: 58,
    justifyContent: "center",
  },
  navIcon: {
    color: "#52616f",
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 32,
  },
  navIconActive: {
    color: "#0ea5e9",
  },
  navLabel: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "900",
  },
  navLabelActive: {
    color: "#ffffff",
  },
  gradeButtonTitle: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 4,
  },
  gradeButtonText: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  progressBand: {
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 18,
    padding: 16,
  },
  progressTitle: {
    color: "#0f172a",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 10,
  },
  progressTrack: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    height: 12,
    marginBottom: 10,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "#16a34a",
    height: 12,
  },
  progressText: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  lessonLayout: {
    gap: 16,
  },
  unitList: {
    gap: 12,
  },
  unitSection: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    paddingBottom: 12,
  },
  lessonButton: {
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    padding: 12,
  },
  lessonButtonTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  lessonButtonMeta: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
    textTransform: "capitalize",
  },
  lessonButtonGoal: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 5,
  },
  lessonPanel: {
    backgroundColor: "#ffffff",
    padding: 16,
  },
  lessonConcept: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  lessonTitle: {
    color: "#0f172a",
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 8,
  },
  lessonExplain: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 14,
  },
  exampleBlock: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    marginBottom: 16,
    paddingBottom: 4,
  },
  questionBlock: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    marginBottom: 12,
    paddingBottom: 14,
  },
  lessonSection: {
    marginBottom: 18,
  },
  quizSection: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    marginBottom: 18,
    padding: 12,
  },
  exampleLabel: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  exampleText: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
    marginBottom: 10,
  },
  tenFrame: {
    borderColor: "#0f172a",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    flexWrap: "wrap",
    height: 116,
    marginBottom: 16,
    maxWidth: 280,
    overflow: "hidden",
    width: "100%",
  },
  tenCell: {
    alignItems: "center",
    borderColor: "#0f172a",
    borderWidth: 1,
    height: 56,
    justifyContent: "center",
    width: "20%",
  },
  tenCellFilled: {
    backgroundColor: "#f97316",
  },
  tenCellAdded: {
    backgroundColor: "#38bdf8",
  },
  visualRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  visualOperator: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "900",
  },
  dotWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    maxWidth: 180,
  },
  dot: {
    alignItems: "center",
    backgroundColor: "#22c55e",
    borderRadius: 14,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  dotRemoved: {
    backgroundColor: "#fecaca",
    borderColor: "#dc2626",
    borderWidth: 2,
  },
  removedMark: {
    color: "#991b1b",
    fontSize: 16,
    fontWeight: "900",
  },
  numberLine: {
    borderTopColor: "#0f172a",
    borderTopWidth: 3,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 44,
    marginTop: 34,
    paddingTop: 0,
  },
  numberTick: {
    alignItems: "center",
    marginTop: -12,
    width: 14,
  },
  tickLine: {
    backgroundColor: "#0f172a",
    height: 16,
    width: 2,
  },
  tickText: {
    color: "#0f172a",
    fontSize: 9,
    fontWeight: "800",
    marginTop: 3,
  },
  jumpText: {
    bottom: -34,
    color: "#2563eb",
    fontSize: 14,
    fontWeight: "800",
    left: 0,
    position: "absolute",
  },
  baseTenRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 18,
    marginBottom: 16,
  },
  tenRodColumn: {
    flexDirection: "row",
    gap: 8,
  },
  tenRod: {
    backgroundColor: "#60a5fa",
    borderColor: "#1d4ed8",
    borderRadius: 6,
    borderWidth: 1,
    height: 110,
    width: 24,
  },
  skipRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 16,
  },
  skipBubble: {
    alignItems: "center",
    backgroundColor: "#e0f2fe",
    borderColor: "#0284c7",
    borderRadius: 8,
    borderWidth: 1,
    height: 54,
    justifyContent: "center",
    width: 54,
  },
  skipText: {
    color: "#075985",
    fontSize: 18,
    fontWeight: "900",
  },
  skipNext: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "900",
  },
  measurementBox: {
    marginBottom: 16,
  },
  pencil: {
    backgroundColor: "#facc15",
    borderRadius: 8,
    height: 22,
    marginBottom: 10,
    maxWidth: 260,
    width: "90%",
  },
  clipRow: {
    flexDirection: "row",
    gap: 6,
  },
  paperClip: {
    borderColor: "#64748b",
    borderRadius: 10,
    borderWidth: 2,
    height: 34,
    width: 20,
  },
  clock: {
    alignSelf: "flex-start",
    borderColor: "#0f172a",
    borderRadius: 70,
    borderWidth: 3,
    height: 140,
    marginBottom: 16,
    position: "relative",
    width: 140,
  },
  clockNumber: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "900",
    position: "absolute",
  },
  clockTwelve: {
    left: 58,
    top: 8,
  },
  clockThree: {
    right: 12,
    top: 60,
  },
  clockSix: {
    bottom: 8,
    left: 64,
  },
  clockNine: {
    left: 12,
    top: 60,
  },
  hourHand: {
    backgroundColor: "#0f172a",
    height: 4,
    left: 70,
    position: "absolute",
    top: 68,
    width: 42,
  },
  minuteHand: {
    backgroundColor: "#0f172a",
    height: 54,
    left: 68,
    position: "absolute",
    top: 18,
    width: 4,
  },
  shapeRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 18,
    marginBottom: 16,
  },
  triangle: {
    borderBottomColor: "#f97316",
    borderBottomWidth: 58,
    borderLeftColor: "transparent",
    borderLeftWidth: 32,
    borderRightColor: "transparent",
    borderRightWidth: 32,
    height: 0,
    width: 0,
  },
  squareShape: {
    backgroundColor: "#22c55e",
    height: 58,
    width: 58,
  },
  circleShape: {
    backgroundColor: "#60a5fa",
    borderRadius: 29,
    height: 58,
    width: 58,
  },
  practicePrompt: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 25,
    marginBottom: 12,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 12,
  },
  choiceButton: {
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 78,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  choiceCorrect: {
    backgroundColor: "#bbf7d0",
    borderColor: "#16a34a",
  },
  choiceIncorrect: {
    backgroundColor: "#fecaca",
    borderColor: "#dc2626",
  },
  choiceButtonText: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "900",
  },
  feedbackText: {
    color: "#334155",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 22,
    marginBottom: 12,
  },
  masteryBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    marginTop: 4,
    padding: 12,
  },
  masteryLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 3,
    textTransform: "uppercase",
  },
  masteryValue: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
});
